title: BetterMeower Project
author: BetterMeower Project
description: > # this means to ignore newlines until "baseurl:"
  The official BetterMeower project's website
# social links
github_username:  BetterMeower-Project # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
